apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ea0374swg-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ea0374swg-java-quarkus-gitops